# Generated by Django 4.0.5 on 2022-07-15 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='physical',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
