# Generated by Django 4.0.5 on 2022-07-24 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_orderitem_order_alter_orderitem_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='reserved_by',
            field=models.CharField(default='No one', max_length=100),
        ),
    ]
