# Generated by Django 4.0.5 on 2022-07-18 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customUser',
            fields=[
                ('userId', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=80, unique=True)),
                ('password', models.CharField(max_length=32)),
                ('cpassword', models.CharField(default='null', max_length=32)),
            ],
        ),
    ]
