# Generated by Django 4.0.5 on 2022-07-08 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=80)),
                ('password', models.CharField(max_length=32)),
                ('cpassword', models.CharField(max_length=32)),
            ],
        ),
        migrations.DeleteModel(
            name='userCredentials',
        ),
    ]
