# Generated by Django 4.0.5 on 2022-07-16 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='cpassword',
            field=models.CharField(default='null', max_length=32),
        ),
    ]
