# Generated by Django 4.0.5 on 2022-07-08 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_signup_delete_usercredentials'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='fullname',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='cpassword',
        ),
    ]
